import { DataSource } from "../types/source";
import { ScrapeTask } from "../types/task";
import {
  ActivityLogItem,
  FolkloreItem,
  QueueItem,
  ResourceMetrics,
  SystemStats,
} from "../types/orchestration";

export interface SunCoreState {
  status: "idle" | "processing" | "alert" | "completed";
  energyLevel: number; // 0.0 - 1.0
  pulseSpeed: number;
  flareIntensity: number;
  coronaGlow: number;
  coreTemperature: number; // e.g. 5778 K
  activePipelines: number;
}

export interface OrchestratorState {
  // Navigation & View
  currentView: "orchestrator" | "sources" | "tasks" | "library" | "analytics" | "settings";
  selectedSourceId: string | null;
  focusedSourceId: string | null;
  isAddSourceModalOpen: boolean;
  isCreateTaskModalOpen: boolean;
  simulationSpeed: number; // 1x, 2x, 5x, 0 (paused)
  reducedMotion: boolean;
  soundEnabled: boolean;
  
  // Core Elements
  sunCore: SunCoreState;
  sources: DataSource[];
  activeTask: ScrapeTask;
  tasksList: ScrapeTask[];
  
  // Dashboard Metrics & Telemetry
  stats: SystemStats;
  resources: ResourceMetrics;
  queue: QueueItem[];
  activities: ActivityLogItem[];
  libraryRecords: FolkloreItem[];
  
  // Search & Filter
  searchQuery: string;
}

export const INITIAL_SOURCES: DataSource[] = [
  {
    id: "source-wiki",
    name: "Wikipedia",
    url: "https://en.wikipedia.org/wiki/Category:Indian_folklore",
    type: "website",
    status: "fetching",
    region: "Pan-India",
    language: "en, hi",
    category: "Encyclopedic",
    description: "Crowdsourced historical and cultural folktale summaries with citations and regional taxonomy.",
    orbit: {
      radius: 130,
      angle: 0.45,
      speed: 0.0032,
      inclination: 0.08,
      eccentricity: 1.02,
    },
    rotation: {
      speed: 0.012,
      tilt: 14,
    },
    visual: {
      color: "#10b981",
      glowColor: "#34d399",
      radius: 4.8,
      theme: "emerald-gas",
      iconName: "Globe",
    },
    metrics: {
      pagesProcessed: 412,
      recordsFound: 146,
      errorsCount: 2,
      latencyMs: 140,
      currentRate: 42,
      lastCrawledAt: "2 min ago",
      successRate: 99.1,
    },
    tags: ["folktales", "panchatantra", "jataka", "legends"],
    maxPages: 500,
    maxDepth: 3,
    crawlFrequency: "Daily",
  },
  {
    id: "source-digital-lib",
    name: "Digital Library",
    url: "https://ndl.gov.in/cultural-heritage",
    type: "document_collection",
    status: "idle",
    region: "National",
    language: "Multilingual",
    category: "Government Archive",
    description: "National repository of digitized ancient manuscripts, oral epics, and folkloric literature.",
    orbit: {
      radius: 175,
      angle: 1.9,
      speed: 0.0024,
      inclination: -0.05,
      eccentricity: 0.98,
    },
    rotation: {
      speed: 0.009,
      tilt: 23,
    },
    visual: {
      color: "#38bdf8",
      glowColor: "#60a5fa",
      radius: 5.4,
      theme: "deep-ocean",
      iconName: "BookOpen",
    },
    metrics: {
      pagesProcessed: 289,
      recordsFound: 84,
      errorsCount: 0,
      latencyMs: 220,
      currentRate: 0,
      lastCrawledAt: "18 min ago",
      successRate: 100.0,
    },
    tags: ["manuscripts", "sanskrit", "pali", "epics"],
    maxPages: 300,
    maxDepth: 2,
    crawlFrequency: "Weekly",
  },
  {
    id: "source-archive",
    name: "Archive.org",
    url: "https://archive.org/details/indian-folklore-collection",
    type: "api",
    status: "fetching",
    region: "Global Archives",
    language: "en, bn, ta, mr",
    category: "Historical Books",
    description: "19th & 20th century folkloric surveys, British colonial records, and anthropological field notes.",
    orbit: {
      radius: 225,
      angle: 3.5,
      speed: 0.0018,
      inclination: 0.12,
      eccentricity: 1.05,
    },
    rotation: {
      speed: 0.015,
      tilt: 28,
    },
    visual: {
      color: "#ef4444",
      glowColor: "#f87171",
      ringColor: "#fca5a5",
      hasRings: true,
      ringRadius: 10.5,
      radius: 6.2,
      theme: "crimson-ringed",
      iconName: "Database",
    },
    metrics: {
      pagesProcessed: 560,
      recordsFound: 198,
      errorsCount: 4,
      latencyMs: 310,
      currentRate: 36,
      lastCrawledAt: "1 min ago",
      successRate: 97.8,
    },
    tags: ["surveys", "anthropology", "tales", "colonial-era"],
    maxPages: 1000,
    maxDepth: 4,
    crawlFrequency: "Daily",
  },
  {
    id: "source-gov-portals",
    name: "Government Portals",
    url: "https://ignca.gov.in/divisions/janapada-sampada",
    type: "website",
    status: "analyzing",
    region: "Ministry of Culture",
    language: "hi, en, regional",
    category: "State Portals",
    description: "Indira Gandhi National Centre for the Arts (IGNCA) Janapada Sampada tribal folklore records.",
    orbit: {
      radius: 270,
      angle: 4.8,
      speed: 0.0014,
      inclination: -0.09,
      eccentricity: 0.96,
    },
    rotation: {
      speed: 0.007,
      tilt: 8,
    },
    visual: {
      color: "#a855f7",
      glowColor: "#c084fc",
      radius: 5.8,
      theme: "amethyst-ice",
      iconName: "Landmark",
    },
    metrics: {
      pagesProcessed: 324,
      recordsFound: 112,
      errorsCount: 1,
      latencyMs: 180,
      currentRate: 28,
      lastCrawledAt: "Just now",
      successRate: 99.4,
    },
    tags: ["ignca", "tribal", "crafts", "rituals"],
    maxPages: 400,
    maxDepth: 3,
    crawlFrequency: "Bi-weekly",
  },
  {
    id: "source-cultural-sites",
    name: "Cultural Sites",
    url: "https://sahapedia.org/modules/oral-traditions",
    type: "website",
    status: "active",
    region: "Regional Hubs",
    language: "hi, raj, guj, ben",
    category: "Community Portals",
    description: "Specialized multimedia documentation of living heritage, storytelling practitioners, and oral ballads.",
    orbit: {
      radius: 315,
      angle: 0.95,
      speed: 0.0011,
      inclination: 0.04,
      eccentricity: 1.0,
    },
    rotation: {
      speed: 0.011,
      tilt: 19,
    },
    visual: {
      color: "#3b82f6",
      glowColor: "#60a5fa",
      radius: 5.0,
      theme: "terrestrial-earth",
      iconName: "Compass",
    },
    metrics: {
      pagesProcessed: 430,
      recordsFound: 165,
      errorsCount: 0,
      latencyMs: 160,
      currentRate: 31,
      lastCrawledAt: "4 min ago",
      successRate: 100.0,
    },
    tags: ["sahapedia", "ballads", "bards", "interviews"],
    maxPages: 600,
    maxDepth: 3,
    crawlFrequency: "Daily",
  },
  {
    id: "source-folklore-repos",
    name: "Folklore Repositories",
    url: "https://folklore.org.in/repository",
    type: "api",
    status: "active",
    region: "Southern & Eastern India",
    language: "ta, te, kn, ml, or",
    category: "Folklore Societies",
    description: "Academic folklore congress databases, village deities (Gramadevata) studies, and song metrics.",
    orbit: {
      radius: 360,
      angle: 2.6,
      speed: 0.0009,
      inclination: -0.06,
      eccentricity: 1.01,
    },
    rotation: {
      speed: 0.013,
      tilt: 12,
    },
    visual: {
      color: "#14b8a6",
      glowColor: "#2dd4bf",
      radius: 5.2,
      theme: "toxic-neon",
      iconName: "Layers",
    },
    metrics: {
      pagesProcessed: 378,
      recordsFound: 142,
      errorsCount: 2,
      latencyMs: 195,
      currentRate: 24,
      lastCrawledAt: "5 min ago",
      successRate: 98.7,
    },
    tags: ["gramadevata", "dravidian", "songs", "rituals"],
    maxPages: 450,
    maxDepth: 3,
    crawlFrequency: "Daily",
  },
  {
    id: "source-academic-journals",
    name: "Academic Journals",
    url: "https://journals.sagepub.com/asian-ethnology",
    type: "document_collection",
    status: "analyzing",
    region: "Scholarly",
    language: "en, regional",
    category: "Peer-reviewed",
    description: "Asian Ethnology and Indian Folklore Research Journal peer-reviewed field transcriptions.",
    orbit: {
      radius: 405,
      angle: 5.4,
      speed: 0.00075,
      inclination: 0.11,
      eccentricity: 0.97,
    },
    rotation: {
      speed: 0.008,
      tilt: 25,
    },
    visual: {
      color: "#2563eb",
      glowColor: "#3b82f6",
      radius: 4.6,
      theme: "electric-azure",
      iconName: "GraduationCap",
    },
    metrics: {
      pagesProcessed: 215,
      recordsFound: 72,
      errorsCount: 1,
      latencyMs: 340,
      currentRate: 18,
      lastCrawledAt: "3 min ago",
      successRate: 99.0,
    },
    tags: ["peer-reviewed", "ethnography", "tek", "structuralism"],
    maxPages: 250,
    maxDepth: 2,
    crawlFrequency: "Monthly",
  },
  {
    id: "source-community",
    name: "Community Submissions",
    url: "https://lokkatha.org/community/submissions",
    type: "community",
    status: "idle",
    region: "Grassroots",
    language: "22 Scheduled Languages",
    category: "Direct Submissions",
    description: "Crowdsourced voice recordings, family heirloom stories, and elder oral narratives submitted via Lokkatha app.",
    orbit: {
      radius: 450,
      angle: 1.4,
      speed: 0.0006,
      inclination: -0.04,
      eccentricity: 1.03,
    },
    rotation: {
      speed: 0.010,
      tilt: 16,
    },
    visual: {
      color: "#f59e0b",
      glowColor: "#fbbf24",
      radius: 5.6,
      theme: "golden-dune",
      iconName: "Users",
    },
    metrics: {
      pagesProcessed: 180,
      recordsFound: 94,
      errorsCount: 0,
      latencyMs: 95,
      currentRate: 0,
      lastCrawledAt: "35 min ago",
      successRate: 100.0,
    },
    tags: ["crowdsourced", "audio", "vernacular", "grandparent-tales"],
    maxPages: 500,
    maxDepth: 1,
    crawlFrequency: "Realtime",
  },
  {
    id: "source-news-blogs",
    name: "News & Blogs",
    url: "https://ruralindiaonline.org/en/articles/categories/culture/",
    type: "rss",
    status: "idle",
    region: "Rural Hubs",
    language: "en, hi, mr, bn, or",
    category: "Grassroots Media",
    description: "People's Archive of Rural India (PARI) grassroots reportage on rural folk songs and artisans.",
    orbit: {
      radius: 495,
      angle: 4.1,
      speed: 0.0005,
      inclination: 0.07,
      eccentricity: 0.99,
    },
    rotation: {
      speed: 0.014,
      tilt: 21,
    },
    visual: {
      color: "#f97316",
      glowColor: "#fb923c",
      radius: 4.4,
      theme: "sandstone-canyon",
      iconName: "Newspaper",
    },
    metrics: {
      pagesProcessed: 165,
      recordsFound: 58,
      errorsCount: 0,
      latencyMs: 150,
      currentRate: 0,
      lastCrawledAt: "1 hr ago",
      successRate: 100.0,
    },
    tags: ["pari", "grindmill-songs", "rural", "weaving"],
    maxPages: 300,
    maxDepth: 2,
    crawlFrequency: "Daily",
  },
];

export const INITIAL_ACTIVE_TASK: ScrapeTask = {
  id: "task-raj-folktales-01",
  title: "Scraping Rajasthan Folktales",
  description: "Targeted crawl and deep TEK extraction across Thar desert folklore repositories and digital archives.",
  targetRegion: "Rajasthan (Marwar, Mewar, Shekhawati)",
  sourceIds: ["source-wiki", "source-archive", "source-cultural-sites", "source-gov-portals"],
  status: "running",
  progress: 68,
  stages: [
    {
      id: "stage-connect",
      name: "Connecting to sources",
      status: "completed",
      duration: "12s",
      message: "4 active sockets established with politeness policies",
    },
    {
      id: "stage-fetch",
      name: "Fetching pages",
      status: "completed",
      duration: "1m 24s",
      message: "124 pages downloaded with Playwright dynamic scraper",
    },
    {
      id: "stage-parse",
      name: "Parsing content",
      status: "running",
      duration: "Active...",
      message: "Extracting article text and stripping boilerplate banners",
    },
    {
      id: "stage-extract",
      name: "Extracting entities & TEK",
      status: "pending",
      duration: "Pending",
      message: "LLM prompt extractors targeting characters, motifs & water management",
    },
    {
      id: "stage-store",
      name: "Storing in database",
      status: "pending",
      duration: "Pending",
      message: "Saving canonical JSON records and pgvector embeddings",
    },
  ],
  currentStageIndex: 2,
  startTime: "20:10:00",
  elapsedSeconds: 154,
  pagesProcessed: 124,
  storiesDiscovered: 48,
  currentSource: "Archive.org & Cultural Sites",
  currentOperation: "Extracting story narrative & ATU motif taxonomy",
  errorCount: 0,
};

export const INITIAL_ACTIVITIES: ActivityLogItem[] = [
  {
    id: "act-1",
    timestamp: "20:14:22",
    sourceId: "source-wiki",
    sourceName: "Wikipedia",
    eventType: "fetch",
    message: "Fetched 12 pages under Category:Rajasthani_folktales",
    level: "info",
  },
  {
    id: "act-2",
    timestamp: "20:14:18",
    sourceId: "source-archive",
    sourceName: "Archive.org",
    eventType: "extract",
    message: "Parsing document: Annals and Antiquities of Rajasthan Vol 2",
    level: "info",
  },
  {
    id: "act-3",
    timestamp: "20:14:10",
    sourceId: "source-cultural-sites",
    sourceName: "Cultural Sites",
    eventType: "extract",
    message: "Extracted 3 stories (Mumal-Mahendra, Dhola-Maru, Pabuji)",
    level: "success",
  },
  {
    id: "act-4",
    timestamp: "20:14:07",
    sourceId: "source-news-blogs",
    sourceName: "News & Blogs",
    eventType: "queue",
    message: "Added 14 candidate story URLs to frontier queue",
    level: "info",
  },
  {
    id: "act-5",
    timestamp: "20:14:01",
    sourceId: "source-academic-journals",
    sourceName: "Academic Journals",
    eventType: "validate",
    message: "Analyzing TEK: Johad water structures & Khejri sacred groves",
    level: "success",
  },
  {
    id: "act-6",
    timestamp: "20:13:55",
    sourceId: "source-folklore-repos",
    sourceName: "Folklore Repositories",
    eventType: "store",
    message: "Stored 5 validated records with canonical IDs",
    level: "success",
  },
  {
    id: "act-7",
    timestamp: "20:13:49",
    sourceId: "source-gov-portals",
    sourceName: "Government Portals",
    eventType: "fetch",
    message: "Fetching page 4/10 from IGNCA Tribal Research Division",
    level: "info",
  },
  {
    id: "act-8",
    timestamp: "20:13:42",
    sourceId: "source-community",
    sourceName: "Community Submissions",
    eventType: "connect",
    message: "Connected secure intake stream for Rajasthani voice tales",
    level: "info",
  },
];

export const INITIAL_FOLKLORE_RECORDS: FolkloreItem[] = [
  {
    id: "folk-mumal-mahendra",
    title: "The Legend of Mumal and Mahendra",
    alternateTitle: "मूमल-महेन्द्र की अमर प्रेमकथा",
    folkloreType: "Love Story / Romantic Legend",
    region: ["Rajasthan", "Jaisalmer", "Umerkot"],
    language: ["hi", "raj"],
    sourceName: "Cultural Sites",
    sourceUrl: "https://sahapedia.org/mumal-mahendra",
    discoveredAt: "2026-09-14 20:12:15",
    confidence: 0.96,
    summary: "The tragic love story of Princess Mumal of Lodrawa and Prince Mahendra of Sodha Sodhi, famous for the magical palace Kak Mahal and nocturnal desert rides on the swift camel Cheetal.",
    characters: ["Mumal", "Mahendra", "Cheetal (Camel)", "Sumal"],
    motifs: ["T10 - Falling in love", "H900 - Impossible tasks", "K1300 - Seduction by deception"],
    tekCount: 3,
    verified: true,
  },
  {
    id: "folk-pabuji-rathore",
    title: "The Epic of Pabuji Rathore & Deval Mata",
    alternateTitle: "पाबूजी की पड़ एवं कथा",
    folkloreType: "Heroic Tale / Epic",
    region: ["Rajasthan", "Marwar"],
    language: ["raj", "hi"],
    sourceName: "Archive.org",
    sourceUrl: "https://archive.org/details/epic-of-pabuji",
    discoveredAt: "2026-09-14 20:08:40",
    confidence: 0.98,
    summary: "14th-century hero-deity Pabuji protected the sacred cows of Charani Deval Mata using the black mare Kesar Kalami, revered as protector of pastoral camels and creator of the Phad painting tradition.",
    characters: ["Pabuji Rathore", "Deval Mata", "Jindrav Khichi", "Kesar Kalami"],
    motifs: ["B184.1 - Magic horse", "V220 - Sacrificial protection of livestock"],
    tekCount: 5,
    verified: true,
  },
  {
    id: "folk-khejri-amrita-devi",
    title: "The Bishnoi Sacrifice & The Sacred Khejri Trees",
    alternateTitle: "खेजड़ली का अमर बलिदान",
    folkloreType: "Origin Story / Ecological Legend",
    region: ["Rajasthan", "Jodhpur", "Khejarli"],
    language: ["hi", "raj"],
    sourceName: "Academic Journals",
    sourceUrl: "https://journals.sagepub.com/bishnoi-ecology",
    discoveredAt: "2026-09-14 19:54:10",
    confidence: 0.99,
    summary: "In 1730, Amrita Devi Bishnoi and 363 villagers sacrificed their lives embracing sacred Khejri trees (Prosopis cineraria) to prevent the Maharaja's men from cutting them down, birthing the Chipko philosophy.",
    characters: ["Amrita Devi Bishnoi", "Maharaja Abhai Singh", "Bishnoi Elders"],
    motifs: ["Sacred tree taboo", "Environmental martyrdom", "Coexistence with wildlife"],
    tekCount: 8,
    verified: true,
  },
  {
    id: "folk-bonbibi-sundarbans",
    title: "Bonbibi Jahuranama: Guardian of the Mangroves",
    alternateTitle: "বনবিবি জহুরনামা",
    folkloreType: "Myth / Ritual Narrative",
    region: ["West Bengal", "Sundarbans"],
    language: ["bn"],
    sourceName: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Bonbibi",
    discoveredAt: "2026-09-14 19:40:05",
    confidence: 0.94,
    summary: "Folk deity Bonbibi protects honey gatherers (mouleys) and woodcutters entering the mangrove forests against Dokkhin Rai, the demon-spirit shape-shifting as a royal Bengal tiger.",
    characters: ["Bonbibi", "Shah Jangali", "Dokkhin Rai (Tiger Spirit)", "Dukhe"],
    motifs: ["Forest spirit pact", "Tiger shape-shifter", "Sustainable honey harvesting"],
    tekCount: 6,
    verified: true,
  },
];
